<?xml version="1.0" encoding="utf-8"?><Database Name="University" Class="UniversityDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Course" Member="Courses">
    <Type Name="Course">
      <Column Name="CourseID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="Credits" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Course_CourseInstructor" Member="CourseInstructors" ThisKey="CourseID" OtherKey="CourseID" Type="CourseInstructor" />
      <Association Name="Course_Enrollment" Member="Enrollments" ThisKey="CourseID" OtherKey="CourseID" Type="Enrollment" />
      <Association Name="Department_Course" Member="Department" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="Department" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CourseInstructor" Member="CourseInstructors">
    <Type Name="CourseInstructor">
      <Column Name="CourseID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="InstructorID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Course_CourseInstructor" Member="Course" ThisKey="CourseID" OtherKey="CourseID" Type="Course" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Person_CourseInstructor" Member="Person" ThisKey="InstructorID" OtherKey="ID" Type="Person" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Department" Member="Departments">
    <Type Name="Department">
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Budget" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="InstructorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RowVersion" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Association Name="Department_Course" Member="Courses" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="Course" />
      <Association Name="Person_Department" Member="Person" ThisKey="InstructorID" OtherKey="ID" Type="Person" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Enrollment" Member="Enrollments">
    <Type Name="Enrollment">
      <Column Name="EnrollmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CourseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Grade" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Course_Enrollment" Member="Course" ThisKey="CourseID" OtherKey="CourseID" Type="Course" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Person_Enrollment" Member="Person" ThisKey="StudentID" OtherKey="ID" Type="Person" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OfficeAssignment" Member="OfficeAssignments">
    <Type Name="OfficeAssignment">
      <Column Name="InstructorID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Person_OfficeAssignment" Member="Person" ThisKey="InstructorID" OtherKey="ID" Type="Person" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Person" Member="Persons">
    <Type Name="Person">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HireDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EnrollmentDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Discriminator" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Association Name="Person_CourseInstructor" Member="CourseInstructors" ThisKey="ID" OtherKey="InstructorID" Type="CourseInstructor" />
      <Association Name="Person_Department" Member="Departments" ThisKey="ID" OtherKey="InstructorID" Type="Department" />
      <Association Name="Person_Enrollment" Member="Enrollments" ThisKey="ID" OtherKey="StudentID" Type="Enrollment" />
      <Association Name="Person_OfficeAssignment" Member="OfficeAssignment" ThisKey="ID" OtherKey="InstructorID" Type="OfficeAssignment" Cardinality="One" />
    </Type>
  </Table>
</Database>